# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


Coin =  Table('Coin', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=150), primary_key=False, nullable=False),
            Column(u'symbol', CHAR(length=3), primary_key=False, nullable=False),
            Column(u'profitability', INTEGER(), primary_key=False, nullable=False),
    
    
    )
Index(u'name', Coin.c.name, unique=True)
Index(u'symbol', Coin.c.symbol, unique=True)


CoinService =  Table('CoinService', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'coinId', INTEGER(), primary_key=False, nullable=False),
            Column(u'serviceId', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'coinId'], [u'MultiPool.Coin.id'], name=u'CoinService_ibfk_1'),
            ForeignKeyConstraint([u'serviceId'], [u'MultiPool.Service.id'], name=u'CoinService_ibfk_2'),
    
    )
Index(u'uniqService', CoinService.c.serviceId, unique=True)
Index(u'coinId', CoinService.c.coinId, CoinService.c.serviceId, unique=True)


Domain =  Table('Domain', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=250), primary_key=False, nullable=False),
    
    
    )
Index(u'name', Domain.c.name, unique=True)


Email =  Table('Email', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'domainId', INTEGER(), primary_key=False, nullable=False),
            Column(u'user', VARCHAR(length=250), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'domainId'], [u'MultiPool.Domain.id'], name=u'Email_ibfk_1'),
    
    )
Index(u'domainId', Email.c.domainId, Email.c.user, unique=True)


Host =  Table('Host', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=250), primary_key=False, nullable=False),
    
    
    )
Index(u'name', Host.c.name, unique=True)


Name =  Table('Name', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=100), primary_key=False, nullable=False),
    
    
    )
Index(u'name', Name.c.name, unique=True)


Service =  Table('Service', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'serviceTypeId', INTEGER(), primary_key=False, nullable=False),
            Column(u'port', INTEGER(), primary_key=False, nullable=False),
            Column(u'hostId', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'hostId'], [u'MultiPool.Host.id'], name=u'Service_ibfk_2'),
            ForeignKeyConstraint([u'serviceTypeId'], [u'MultiPool.ServiceType.id'], name=u'Service_ibfk_1'),
    
    )
Index(u'serviceTypeId', Service.c.serviceTypeId, unique=False)
Index(u'hostId', Service.c.hostId, unique=False)


ServiceType =  Table('ServiceType', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=250), primary_key=False, nullable=False),
    
    
    )
Index(u'name', ServiceType.c.name, unique=True)


User =  Table('User', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'username', VARCHAR(length=250), primary_key=False, nullable=False),
            Column(u'password', VARCHAR(length=250), primary_key=False, nullable=False),
    
    
    )
Index(u'username', User.c.username, unique=True)


UserFirstName =  Table('UserFirstName', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'userId', INTEGER(), primary_key=False, nullable=False),
            Column(u'nameId', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'userId'], [u'MultiPool.User.id'], name=u'UserFirstName_ibfk_1'),
            ForeignKeyConstraint([u'nameId'], [u'MultiPool.Name.id'], name=u'UserFirstName_ibfk_2'),
    
    )
Index(u'userId', UserFirstName.c.userId, unique=False)
Index(u'nameId', UserFirstName.c.nameId, unique=False)


Worker =  Table('Worker', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'userId', INTEGER(), primary_key=False, nullable=False),
            Column(u'name', VARCHAR(length=200), primary_key=False, nullable=False),
            Column(u'password', VARCHAR(length=200), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'userId'], [u'MultiPool.User.id'], name=u'Worker_ibfk_1'),
    
    )
Index(u'uniqueUserWorker', Worker.c.userId, Worker.c.name, unique=True)


WorkerCoin =  Table('WorkerCoin', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'workerId', INTEGER(), primary_key=False, nullable=False),
            Column(u'coinId', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'workerId'], [u'MultiPool.Worker.id'], name=u'WorkerCoin_ibfk_1'),
            ForeignKeyConstraint([u'coinId'], [u'MultiPool.Coin.id'], name=u'WorkerCoin_ibfk_2'),
    
    )
Index(u'coinId', WorkerCoin.c.coinId, unique=False)
Index(u'workerId', WorkerCoin.c.workerId, WorkerCoin.c.coinId, unique=True)

